from typing import Any, List

from kiteconnect import KiteConnect

from .config import Settings


class KiteClient:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        if not self.settings.kite_api_key:
            raise RuntimeError("KITE_API_KEY is missing in environment/.env")

        self.kite = KiteConnect(api_key=self.settings.kite_api_key)

    def authenticate(self) -> None:
        """
        Set the access token on the client, using the file generated by
        scripts/get_kite_access_token.py.
        """
        token_path = self.settings.kite_access_token_path

        if not token_path.exists():
            raise RuntimeError(
                f"Access token file not found at {token_path}.\n"
                "Run: python scripts/get_kite_access_token.py"
            )

        access_token = token_path.read_text(encoding="utf-8").strip()
        if not access_token:
            raise RuntimeError(
                f"Access token file {token_path} is empty. "
                "Re-run get_kite_access_token.py."
            )

        self.kite.set_access_token(access_token)

    def fetch_instruments_nfo(self) -> List[dict[str, Any]]:
        """Return full instruments dump for NFO (F&O segment)."""
        return self.kite.instruments("NFO")

    def fetch_instruments_equity(self) -> List[dict[str, Any]]:
        """
        Return full instruments dump for NSE equities.
        (You can add BSE later if needed.)
        """
        return self.kite.instruments("NSE")
